// <auto-generated />
namespace BillsPaymentSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedCollections : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedCollections));
        
        string IMigrationMetadata.Id
        {
            get { return "201611141919425_changedCollections"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
